### ISSUE TITLE
Outdated documentation with Bdelete and Bwipeout

### ISSUE THREAD

**Issue by chmouel** [famiu/bufdelete.nvim#11]
I could not find the Bdelete and Bwipeout function but BufferDelete and BufferWipeout, i guess the documentation is outdated?

**Comment by famiu** [comment]
Nope, the documentation is fine. Can you reproduce your issue with a minimal config? If so, could you share that minimal config here?

**Comment by famiu** [comment]
Closing this issue due to lack of information and inactivity, feel free to open a new issue with more details if your problem persists
