### ISSUE TITLE
Cannot close unlisted buffers

### ISSUE THREAD

**Issue by EtiamNullam** [famiu/bufdelete.nvim#15]
Unlisted buffers, like started from `:help` or `fern` plugin, won't close.

### Steps to reproduce:

1. Open unlisted buffer via `:help`
2. Try closing with `:Bdelete`
3. Notice nothing happens

### Workaround

1. Open unlisted buffer via `:help`
2. **Make current buffer `listed` by `setlocal buflisted` or `lua vim.o.buflisted = true`**
3. Try closing with `:Bdelete`
4. Notice buffer is closed as expected

**Comment by famiu** [comment]
should be fixed now
