### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Slushee-a** [famiu/bufdelete.nvim#26]
**Neovim version**
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

**Describe the bug**
Neovim shows a warning when opened: Error detected while processing [config file]
When trying to update vim-plug, this error is shown:
```
Error detected while processing /home/slushee/.config/nvim/init.vim:
bufdelete.nvim: No buffers were deleted
```
The error doesn't happen when I comment out 
```lua
require('bufdelete').bufdelete(0, true)
```

**To Reproduce**
1. Install budelete.nvim with vim plug
2. Add `require('bufdelete').bufdelete(0, true)` to the config file
3. Open nvim / try to update vim-plug

**Expected behavior**
No error ocurring

**Does this error occur in the minimal init file?**
It does not.

**Screenshots**
![image](https://user-images.githubusercontent.com/55996847/195951068-353662e8-236a-4738-afea-c06f33ffb619.png)
![image](https://user-images.githubusercontent.com/55996847/195951212-4b4616e0-5b68-49ab-aa77-32b0730eb35c.png)
![image](https://user-images.githubusercontent.com/55996847/195951320-1eb5dd6d-53e7-47ef-a3db-5beb2f4c87c9.png)

**Additional context**
This had never happened until not too long ago.

**Comment by famiu** [comment]
Why would you put `require('bufdelete').bufdelete(0)` in your config file?

Also, there is no bug, it is an issue with your config. There is no buffer being deleted so this is perfectly expected behavior.

**Comment by Slushee-a** [comment]
Oh, I thought that was supposed to go in the config. I've had it there for the longest time and it hasn't complained once. 
Thanks! This was just me being dumb
