### ISSUE TITLE
[Bug] Error message everytime i start nvim

### ISSUE THREAD

**Issue by PumpedSardines** [famiu/bufdelete.nvim#27]
**Neovim version**
The output of `nvim --version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Does this error occur in the minimal init file?**
Use the following commands to download the minimal init file provided by bufdelete:
`curl -fLO https://raw.githubusercontent.com/famiu/bufdelete.nvim/master/minimal_init.lua`

Modify the file to your needs (if necessary), then load Neovim using:
`nvim --noplugin -u minimal_init.lua`

And check if your issue still occurs.

**Provide modified minimal_init.lua**
If you modified the minimal_init.lua that bufdelete provides by default in order to fit your configuration, put it here. Otherwise ignore this part.

**Screenshots**

**Additional context**
Add any other context about the problem here (eg: other plugins that may conflict with this plugin, configuration options that you think might cause the issue, etc.).

**Comment by famiu** [comment]
Closed due to not providing enough info

**Comment by PumpedSardines** [comment]
Must've accidentally submited this...
