### ISSUE TITLE
[Feature] If use the Bdelete in a modified buffer, could there be a UI selector?

### ISSUE THREAD

**Issue by Fau818** [famiu/bufdelete.nvim#31]
**Is your feature request related to a problem? Please describe.**

If I try to use `Bdelete` in a modified buffer, some options will occur at the bottom of my terminal window. But since I use `Bdelete` via a keymap, it is hard for me to notice the bottom options.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/75115028/204234852-4dc5e7c6-ab0f-4765-81e7-a3bdec683ac9.png">

---

**Describe the solution you'd like**

I would like a pop-up menu so that I can see the options well and select them. Just like the following image. (The [dressing.nvim](https://github.com/stevearc/dressing.nvim) plugin is used as the selector in the image.)

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/75115028/204237299-87930a01-ee68-4fad-bf2b-d80e0e13f7d6.png">

---

Can this be achieved?

**Comment by famiu** [comment]
Sure. Though I'm busy now so I can't work on it. PR welcome.

**Comment by Fau818** [comment]
Thank you for your reply! After some time to get used to it, I think this issue is no longer necessary. And #33 also solved my problem very well. Thank you again for providing such a great plugin!
