### ISSUE TITLE
How could you delete all buffers other than the current one?

### ISSUE THREAD

**Issue by serhez** [famiu/bufdelete.nvim#39]
I have tried ```<cmd>%bdelete | e # | normal `"<cr>``` and it works, but when plugging in `Bdelete` instead of `bdelete` into that expression, I get the error `bufdelete.nvim: Cannot use buffer name and buffer number at the same time`. Is there a way to achieve this when using `Bdelete`?

Thanks!

**Comment by famiu** [comment]
should be fixed now
