### ISSUE TITLE
Show wrong next buffer

### ISSUE THREAD

**Issue by Nguyen-Hoang-Nam** [famiu/bufdelete.nvim#4]
![ls](https://user-images.githubusercontent.com/74345759/126578347-a369742a-b5fc-4281-b4f2-dd8fc3f02df8.png)

However, `vim.api.nvim_buf_is_loaded(2)` return true. Therefore, when I delete buffer 29, buffer 2 will show next. I checked `nvim-bufferline` and found that they use `vim.bo[buf].buflisted and vim.api.nvim_buf_is_valid(buf)`.

![tree](https://user-images.githubusercontent.com/74345759/126578685-34e9bd88-fd99-4c49-b400-0089de37285b.png)

**Comment by famiu** [comment]
Can you check if #5 works and whether it fixes your issue. If it does, I can merge the PR

**Comment by Nguyen-Hoang-Nam** [comment]
@famiu I tried and it's working fine now
