### ISSUE TITLE
[Bug] After `BDelete`, focus will always go to first buffer

### ISSUE THREAD

**Issue by keaising** [famiu/bufdelete.nvim#45]
**Neovim version**
The output of `nvim --version`.

I use nightly, but it can be reproduce in 0.9.1 stable
```
NVIM v0.10.0-dev-585+g2e055e49a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/__w/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/build/src/nvim/auto -I/__w/neovim/neovim/build/include -I/__w/neovim/neovim/build/cmake.config -I/__w/neovim/neovim/src -I/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Describe the bug**

 from 

In the past, if I run `:BDelete`, current buffer will be deleted and I will be redirected to latest buffer I used, but from this commit: https://github.com/famiu/bufdelete.nvim/commit/4549ea1ee67c5132d4717595dc70216a88abd3b0 ,  `BDelete`  will always go to the first buffer in my nvim instance.

**To Reproduce**
1. Open file1, file2, file3, file4 one by one, they will be open in buf1, buf2, buf3, buf4, now focus is on buf4
2. `:BDelete`, buf4 disappear, focus will be on buf1

**Expected behavior**
I hope focus is on  buf3 because buf3 is the latest buf I have worked on.

**Provide a minimal configuration to reproduce the bug**
I use bisect to find the behavior is changed from commit https://github.com/famiu/bufdelete.nvim/commit/4549ea1ee67c5132d4717595dc70216a88abd3b0, commits before this are ok.

**Comment by keaising** [comment]
I'm not sure this is a bug or feature, if it is a feature, could you please provide a option to close buffer to latest buffer I used?

**Comment by famiu** [comment]
It's actually not possible to switch to latest used buffer (to my knowledge) because Neovim doesn't let you order buffers by how recently they were used, but what you can do is switch to the last opened buffer

**Comment by keaising** [comment]
OK, is there any option in `bufdelete.nvim` for switching to the last buffer that was created? I hope it can have the same behavior as the good old days.

**Comment by famiu** [comment]
> It's actually not possible to switch to latest used buffer (to my knowledge) because Neovim doesn't let you order buffers by how recently they were used, but what you can do is switch to the last buffer that was created

I was actually incorrect about this, it is possible to use the most recent buffer. I will make a PR for it soon.
