### ISSUE TITLE
[Feature] Provide a hook to ignore layout keep

### ISSUE THREAD

**Issue by Shatur** [famiu/bufdelete.nvim#46]
**Is your feature request related to a problem? Please describe.**
Sometimes you have buffers for which you don't want to keep the layout, like Neogit or quickfix.

**Describe the solution you'd like**
It would be great to provide a hook, so users can decide to keep the layout or not.

**Describe alternatives you've considered**
Provide automatic integration with https://github.com/stevearc/stickybuf.nvim that I use.

**Comment by famiu** [comment]
Just use `:bdelete` / `:bwipeout`?

**Comment by Shatur** [comment]
I can, but it would be more convenient to have a single command with a smart behavior that I can map to a hotkey.

**Comment by famiu** [comment]
Just... create a function that does this and map it to a key then?

I don't plan to implement this as the sole purpose of this plugin is to do the exact opposite of what you're asking for

**Comment by Shatur** [comment]
I can do so, in my opinion a bit smarter behavior would be better.
For example you opened a quickfix a want to close it - you need to think what to use `:bdelete` or `:Bdelete`. And if you perefer to have a hotkey, it's two hotkeys instead of one. Of course I can create my `:BSmartDelete`, but I believe it's what most people want, this is why I suggested to have this feature built-in.
