### ISSUE TITLE
[Bug] Deleting a buffer that set 'bufhidden=delete' will trigger Vim error E516.

### ISSUE THREAD

**Issue by gh-liu** [famiu/bufdelete.nvim#51]
**Neovim version**
NVIM v0.10.0-dev-2175+gc8a27bae3

**Describe the bug**

E5108: Error executing lua: ...al/share/nvim/lazy/bufdelete.nvim/lua/bufdelete/init.lua:151: Vim:E516: No buffers were deleted
stack traceback:
        [C]: in function 'bdelete'
        ...al/share/nvim/lazy/bufdelete.nvim/lua/bufdelete/init.lua:151: in function 'buf_kill'
        ...al/share/nvim/lazy/bufdelete.nvim/lua/bufdelete/init.lua:230: in function 'bufdelete'

**To Reproduce**
1. Open a buffer
2. Run `:set bufhidden=delete`
3. Run `:Bdelete`

**Expected behavior**
No error is triggered.

**Provide a minimal configuration to reproduce the bug**

**Screenshots**

**Additional context**

**Comment by famiu** [comment]
Does #53 fix your problem?

**Comment by vlmonk** [comment]
Based on my tests, #53 fixes this bug.

**Comment by famiu** [comment]
Closed by #53
