### ISSUE TITLE
[Feature] Delete all other buffers

### ISSUE THREAD

**Issue by ecly** [famiu/bufdelete.nvim#54]
**Is your feature request related to a problem? Please describe.**
I'm often having to switch to a new problem/task within the same project and typically want to start this off by deleting all buffers except the one currently in focus, using `:Bdelete`.

**Describe the solution you'd like**
A new command or option for `:Bdelete` like `:Bdelete others`.

**Describe alternatives you've considered**
There are some other plugins that offer this functionality, but seems the functionality could naturally fit into this project as well.
This would would (at least to me) make it a one-stop-shop for buffer deletion.
E.g.:
- https://github.com/kazhala/close-buffers.nvim
- https://github.com/ojroques/nvim-bufdel
- https://github.com/artnez/vim-wipeout

I suppose the functionality probably can be implemented using the exposed lua functions as well (or provided as an example). I haven't ventured into this yet.

**Comment by famiu** [comment]
`%Bd | e#`

**Comment by ecly** [comment]
> %Bd | e#

It gets close, but this has the downside of also closing down `NvimTree`. Thanks though.

**Comment by famiu** [comment]
> > %Bd | e#
> 
> It gets close, but this has the downside of also closing down `NvimTree`. Thanks though.

At that point you'd unfortunately have to write your own lua function that iterates through every buffer, filters out the buffers you don't want to close, and uses `Bdelete` to close the rest. Thankfully it's quite easy to do through Lua, you can likely figure it out yourself. I would also suggest checking `:help lua-guide`, it's very useful.

**Comment by erosinnocenti** [comment]
I also needed this feature, and ended up with something very simple.
You can use this snippet as starting point:
```lua
	local bd = require('bufdelete')

	-- Delete all but current buffer
	local keymap = vim.keymap.set
	local opts = { noremap = true, silent = true }
	keymap("n", "<leader>w", function()
		local bufs = vim.api.nvim_list_bufs()
		local current_buf = vim.api.nvim_get_current_buf()
		for _, i in ipairs(bufs) do
			if i ~= current_buf then
				bd.bufdelete(i, true)
			end
		end
	end, opts)
```
