### ISSUE TITLE
I can't close Netrw with bufdelete function

### ISSUE THREAD

**Issue by gbrlsnchs** [famiu/bufdelete.nvim#9]
I'm not sure if this a problem of this plugin, since I know Netrw is famous for being bugged, but previously I used [vim-bbye](https://github.com/moll/vim-bbye) and was able to successfully close Netrw with `:Bdelete`, although with this implementation it simply won't close, even with `require('bufdelete').bufdelete(0, true)`.

**Comment by famiu** [comment]
This is likely to be a netrw issue, not much I can do to help with it

**Comment by gbrlsnchs** [comment]
Since I stopped using Netrw in favor of Dirvish, I can no longer provide input about this issue, so I'll close it!

Thanks!
